### PR TITLE
Add one more argument, header to request

### LINKED ISSUE #34: Custom headers
Gem should accept custom headers

### PR DESCRIPTION
**Pull request by esdrasedu**
closes #34

### CODE REVIEW

**Comment by jonatandahora** [comment]
+1

**Comment by vpaciulli** [comment]
+1

**Comment by leorog** [comment]
You could update the ```README.md``` explaining how to use this new feature.

**Comment by esdrasedu** [comment]
@leorog is true, we need refactor the README, I create issue for that #36

**Comment by lucca65** [comment]
+1

**Pull request merged**
